FROM openjdk:17.0.2 AS jar_extract
ARG JAR_FILE=./target/app.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM openjdk:17.0.2
COPY --from=jar_extract dependencies ./
COPY --from=jar_extract spring-boot-loader ./
COPY --from=jar_extract snapshot-dependencies ./
COPY --from=jar_extract application ./
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]